CREATE TABLE IF NOT EXISTS profesor (
  id SERIAL PRIMARY KEY,
  rut VARCHAR(12) UNIQUE NOT NULL,
  nombre VARCHAR(120) NOT NULL
);
CREATE TABLE IF NOT EXISTS asignatura (
  id SERIAL PRIMARY KEY,
  codigo VARCHAR(20) UNIQUE NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  creditos INT NOT NULL
);
